pre push validation

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,6 +7,11 @@ echo "🚀 Running pre-push checks..."
 echo "🔧 Building solution..."
 dotnet build --no-restore --configuration Release
 
+if [ "$(git rev-parse --abbrev-ref HEAD)" == 'master' ]; then
+  echo "Cannot push into master branch"
+  exit 1
+fi
+
 if [ $? -ne 0 ]; then
   echo "❌ Build failed. Push blocked."
   echo "👉 Fix build errors before pushing."
